__SYSCALL(0, syscall_windows_create)
__SYSCALL(1, syscall_memory_sbrk)
__SYSCALL(2, syscall_debug_puts)
__SYSCALL(3, syscall_messaging_get)
__SYSCALL(4, syscall_messaging_create)
__SYSCALL(5, syscall_windows_present)